# Generated by Django 5.2 on 2025-09-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[('Дизайн кухни', 'Дизайн кухни'), ('Дизайн зала', 'hall_design'), ('Дизайн санузла', 'bathroom_design'), ('Дизайн кладовой', 'pantry_design'), ('Дизайн балкона', 'balcony_design')], default='Дизайн кухни', max_length=50, verbose_name='Тип дизайна'),
        ),
    ]
